### ISSUE TITLE
Rewrite version-dependent strings into version-independent

### ISSUE THREAD

**Issue by rimas-kudelis** [nguyenq/VietOCR3.NET#5]
There are a few strings in VietOCR and VietOCR.NET, which require updating whenever the version of some external library changes.
Examples that quickly popped of the top of my head are GhostScript-related paragraphs in the manual and the application description in the about dialog, which mentions the version of the Tesseract engine used.
It would be great if these could be rewritten to either not mention the versions at all, or to have a generic placeholder which could be replaced with an actual value at compile- or runtime.
The reason for that is that whenever such string changes, Tx treats is as a new string and presents it for localizers to re-translate, which is quite annoying and often results in the translations on Tx actually being less complete than in Git, because you update these translations manually in Git, yet they remain untranslated in Tx.

**Comment by nguyenq** [comment]
I noticed that too. Will use placeholders where appropriate. The version
numbers mentioned in the readme files also will be handled in a way to
minimize impacts on translations.

Thank you for the suggestions.

**Comment by nguyenq** [comment]
Complete.
