### ISSUE TITLE
Two output file names resolved to the same output path: "obj\Debug\VietOCR.NET.BulkDialog.resources"

### ISSUE THREAD

**Issue by yuxing007** [nguyenq/VietOCR3.NET#9]
I have installed .Net Framework 4.7.1 in Win7-64bit, but when I build solution of VietOCR3.NET 's github code in visual studio 2015. I get the error below:
`Two output file names resolved to the same output path: "obj\Debug\VietOCR.NET.BulkDialog.resources"`
and I also cannot run the Exe of VietOCR.NET in Win7-64bit, but I can run it in Win10-64bit!
 Can you give me answer? Thanks very much!

**Comment by nguyenq** [comment]
We're not seeing the issue. Can you try the suggestions from https://stackoverflow.com/questions/13739794/two-output-file-names-resolved-to-the-same-output?

**Comment by yuxing007** [comment]
I have debug the VietOCR.NET.exe with visual studio 2015 in win7 and get the error as below:
`'An unhandled exception of type 'System.Globalization.CultureNotFoundException' occurred in mscorlib.dll

Additional information: Culture is not supported.`

**Comment by nguyenq** [comment]
Please try the solutions suggested in https://stackoverflow.com/questions/2116821/net-4-0-culturenotfoundexception.

Or find out which Culture is not supported, and then remove all the `.resx` files associated with that Culture from the project.

Or try [VietOCRwpf](https://github.com/nguyenq/VietOCRwpf) project as development on VietOCR3.NET has been stopped.

**Comment by yuxing007** [comment]
I don't know VietOCRwpf before, this is very helpful to me! Thank you very much!
